using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Euler
{
	public class euler2 : problem
	{
		public euler2()
		{
			/*
				Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

				1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

				By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
			 */
			int firstNum = 1;
			int secondNum = 2;
			answer = 2;

			const int fourMill = 4000000;


			while (firstNum + secondNum < fourMill) {
				int temp = firstNum + secondNum;
				if (isEven(temp))
				{
					answer += temp;
				}

				firstNum = secondNum;
				secondNum = temp;
			}

			Console.WriteLine(answer);
		}

		private static int add(int a, int b) {
			return a + b;
		}

		private bool isEven(int a) {
			if (a % 2 == 0) { return true; }else { return false; }
		}


	}
}
